### ISSUE TITLE
openid是什么？

### ISSUE THREAD

**Issue by hanshaoxiao** [xiaoyaobishizhe/teenage_study#1]

**Comment by xiaoyaobishizhe** [comment]
在青年大学习里，一个微信号对应着一个openid，openid是oauth认证里面的，用于第三方登入的

**Comment by xiaoyaobishizhe** [comment]
> _No description provided._



> _No description provided._

在青年大学习里，一个微信号对应着一个openid，openid是oauth认证里面的，用于第三方登入的

**Comment by hanshaoxiao** [comment]
明白了 thanks
