### ISSUE TITLE
查询openid和course错误

### ISSUE THREAD

**Issue by keeper-jie** [xiaoyaobishizhe/teenage_study#3]
安装软件按照您说的操作之后，查询不到openid=，course
打开湖南青年团课之后
![47R4SJHHR2YEDE%E UJ`(I7](https://user-images.githubusercontent.com/33612777/142762167-24bc2b06-8f4f-4029-9b94-e888820fa0a7.jpg)
搜索course：
![ANS4$DYQ{4T_( J~$3MU3 P](https://user-images.githubusercontent.com/33612777/142762171-1ef5bc1e-3d4a-4545-b51b-964886576d8e.jpg)
结果：
![15WC@I2Y3APT`JH)CT`AB45](https://user-images.githubusercontent.com/33612777/142762241-0bfae21d-7ed2-4a14-a37f-31dcec5b9b6d.jpg)

**Comment by xiaoyaobishizhe** [comment]
> 安装软件按照您说的操作之后，查询不到openid=，course 打开湖南青年团课之后 ![47R4SJHHR2YEDE%E UJ(I7](https://user-images.githubusercontent.com/33612777/142762167-24bc2b06-8f4f-4029-9b94-e888820fa0a7.jpg) 搜索course： ![ANS4$DYQ{4T_( J~$3MU3 P](https://user-images.githubusercontent.com/33612777/142762171-1ef5bc1e-3d4a-4545-b51b-964886576d8e.jpg) 结果： ![15WC@I2Y3APTJH)CT`AB45](https://user-images.githubusercontent.com/33612777/142762241-0bfae21d-7ed2-4a14-a37f-31dcec5b9b6d.jpg)

你应该没有安装证书，如果你已经安装了证书，你先不要使用过滤功能，用我下面的办法试一下，下面的过程是我刚刚测试的。

安装证书前必须设置手机的锁屏密码

![Screenshot_20211122_203512](https://user-images.githubusercontent.com/77526176/142863030-8fc3a3ad-f6b3-4aea-9ce2-4b0051763d18.jpg)

顺便设置一下只抓取微信的数据包

![Screenshot_20211122_203524](https://user-images.githubusercontent.com/77526176/142863147-52d814de-84bd-4918-b9b9-5e94c5d9cfb0.jpg)

然后开始抓包，抓的差不多的时候，打开抓包软件，此时不用过滤，用搜索功能，搜索`openid=`，然后以文本的格式查看响应体内容。

![Screenshot_20211122_203411](https://user-images.githubusercontent.com/77526176/142863598-4ef77fbc-ad20-46cf-86f9-a7a4b863d67b.jpg)

**Comment by keeper-jie** [comment]
刚刚我马上就去试了一下，怎么安装证书呢，

我用的红米note8 pro，在设置里面搜索了安装ca证书，然后进入里面没有找到该软件对应的证书，能麻烦您发我一份么？google了问题之后表示好像是因为Android 11需要开放root权限才能找到文件，这个就比较麻烦了，我想您先发我一份软件的ca证书我单独安装一下，还不行的话只能参考google里面的，用面具或者什么其它的手段配置好证书文件了。

然后还有一个问题，您的这个教程是说，需要打开一个视频，然后查看openid和course，这个course有没有规律呢，还是每次刷一个视频，需要先用手机上抓包软件获取数据，然后跑python脚本。
如果有规律的话，我这边就能直接写入您的示例了，到时候我也可以帮您完善这部分的操作说明md文件

证书可以麻烦您发我一下么，邮箱747055484@qq.com，或者加我QQ，解决问题之后给您一些辛苦费

最后就是，我尝试了手动刷第十二季第八期，视频中间的问题回答了，然后课后作业也做了，是因为我中间错了一个题目么，没有历史记录，想问问您这个脚本可不可以自动跳过问题，然后获取积分和课程观看记录，辛苦了


![图片](https://user-images.githubusercontent.com/33612777/142865183-4d68d633-a094-42ab-8748-decef41a682c.png)

**Comment by xiaoyaobishizhe** [comment]
> 刚刚我马上就去试了一下，怎么安装证书呢，
> 
> 我用的红米note8 pro，在设置里面搜索了安装ca证书，然后进入里面没有找到该软件对应的证书，能麻烦您发我一份么？google了问题之后表示好像是因为Android 11需要开放root权限才能找到文件，这个就比较麻烦了，我想您先发我一份软件的ca证书我单独安装一下，还不行的话只能参考google里面的，用面具或者什么其它的手段配置好证书文件了。
> 
> 然后还有一个问题，您的这个教程是说，需要打开一个视频，然后查看openid和course，这个course有没有规律呢，还是每次刷一个视频，需要先用手机上抓包软件获取数据，然后跑python脚本。 如果有规律的话，我这边就能直接写入您的示例了，到时候我也可以帮您完善这部分的操作说明md文件
> 
> 证书可以麻烦您发我一下么，邮箱[747055484@qq.com](mailto:747055484@qq.com)，或者加我QQ，解决问题之后给您一些辛苦费
> 
> 最后就是，我尝试了手动刷第十二季第八期，视频中间的问题回答了，然后课后作业也做了，是因为我中间错了一个题目么，没有历史记录，想问问您这个脚本可不可以自动跳过问题，然后获取积分和课程观看记录，辛苦了
> 
> ![图片](https://user-images.githubusercontent.com/33612777/142865183-4d68d633-a094-42ab-8748-decef41a682c.png)

已回复邮箱
