### ISSUE TITLE
redmi 8 pro(Android 11)安装您给的HttpCanary无法安装根证书

### ISSUE THREAD

**Issue by keeper-jie** [xiaoyaobishizhe/teenage_study#4]
按照您发给我的邮箱中的文件，参考网上操作[https://zhuanlan.zhihu.com/p/363266700](https://zhuanlan.zhihu.com/p/363266700)在手机上显示安装ca证书成功，在软件里面还算是显示根证书未安装，具体操作视频我已经发到您邮箱了，如果能解决的话，万分感谢

问题已经定位了就是我的手机上安装CA证书之后，软件还是显示未安装，我将您给我的文件和HttpCanary自带的pem文件在电脑上查看，内容都是一样的就是名字不一样，我两个CA证书都安装了软件还是显示未安装

没有安装证书的话，我用微信青年大学习查看了一下，找不到openid=，

之后我打算用我的备用机（Android版本比较低）再重新操作一下看能不能解决

**Comment by xiaoyaobishizhe** [comment]
其实没必要吊死在一棵树上，反正原因肯定是手机问题，只需换个手机就行，如果没有满足条件的手机的话，可以在电脑上随便安装一个手机模拟器，如雷电模拟器

**Comment by keeper-jie** [comment]
okk，辛苦，我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoyaobishizhe/teenage_study"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 中午11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaoyaobishizhe/teenage_study] redmi 8 pro(Android 11)安装您给的HttpCanary无法安装根证书 (Issue #4)





 
其实没必要吊死在一棵树上，反正原因肯定是手机问题，只需换个手机就行，如果没有满足条件的手机的话，可以在电脑上随便安装一个手机模拟器，如雷电模拟器
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
